# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20191010_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='菜单权重'),
        ),
    ]
